package pojo;
// Generated Oct 22, 2020 6:44:34 PM by Hibernate Tools 4.3.1

import DAO.DAOPasien;
import java.util.List;
import javax.faces.bean.ManagedBean;




/**
 * DataPasien generated by hbm2java
 */
@ManagedBean
public class DataPasien  implements java.io.Serializable {


     private Integer idPasien;
     private String noIdentitas;
     private String namaPasien;
     private String email;
     private String noHp;
     private String alamat;
     private String tglLahir;
     private String jenisKelamin;
     private String jenisKulit;
     private String pekerjaan;

     public String save_pasien(){
         DAOPasien add =new DAOPasien();
         add.add_pasien(this);
         return "DataPasienAdmin";
     }
     public String save_pasienuser(){
         DAOPasien add =new DAOPasien();
         add.add_pasien(this);
         return "LihatPasien";
     }
     public List<DataPasien> getAllRecords(){
         DAOPasien pass = new DAOPasien();
         List<DataPasien> lPass = pass.retrieveDataPasien();
         return lPass;
     }
     public String getById(){
         String ID_Pasien = idPasien.toString();
         DAOPasien pass = new DAOPasien();
           List<DataPasien> lPass = pass.getbyID(ID_Pasien);
            idPasien = lPass.get(0).idPasien;
           noIdentitas = lPass.get(0).noIdentitas;
           namaPasien = lPass.get(0).namaPasien;
           email = lPass.get(0).email;
           noHp = lPass.get(0).noHp;
           alamat = lPass.get(0).alamat;
           tglLahir = lPass.get(0).tglLahir;
           jenisKelamin = lPass.get(0).jenisKelamin;
           jenisKulit = lPass.get(0).jenisKulit;
           pekerjaan = lPass.get(0).pekerjaan;
           
            return "EditDataPasien";
     }
     public String edit(){
            
         DAOPasien pass = new DAOPasien();
         pass.editPasien(this);
         noIdentitas="";
         namaPasien="";
         email="";
         noHp="";
         alamat="";
         tglLahir="";
         jenisKelamin="";
         jenisKulit="";
         pekerjaan="";
         return "DataPasienAdmin";
     }
         public void delete(int id){
   
         DAOPasien dtr = new DAOPasien();
         dtr.deletePasien(id);
         
     }
    public DataPasien() {
    }

    public DataPasien(String noIdentitas, String namaPasien, String email, String noHp, String alamat, String tglLahir, String jenisKelamin, String jenisKulit, String pekerjaan) {
       this.noIdentitas = noIdentitas;
       this.namaPasien = namaPasien;
       this.email = email;
       this.noHp = noHp;
       this.alamat = alamat;
       this.tglLahir = tglLahir;
       this.jenisKelamin = jenisKelamin;
       this.jenisKulit = jenisKulit;
       this.pekerjaan = pekerjaan;
    }
   
    public Integer getIdPasien() {
        return this.idPasien;
    }
    
    public void setIdPasien(Integer idPasien) {
        this.idPasien = idPasien;
    }
    public String getNoIdentitas() {
        return this.noIdentitas;
    }
    
    public void setNoIdentitas(String noIdentitas) {
        this.noIdentitas = noIdentitas;
    }
    public String getNamaPasien() {
        return this.namaPasien;
    }
    
    public void setNamaPasien(String namaPasien) {
        this.namaPasien = namaPasien;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getNoHp() {
        return this.noHp;
    }
    
    public void setNoHp(String noHp) {
        this.noHp = noHp;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }
    public String getTglLahir() {
        return this.tglLahir;
    }
    
    public void setTglLahir(String tglLahir) {
        this.tglLahir = tglLahir;
    }
    public String getJenisKelamin() {
        return this.jenisKelamin;
    }
    
    public void setJenisKelamin(String jenisKelamin) {
        this.jenisKelamin = jenisKelamin;
    }
    public String getJenisKulit() {
        return this.jenisKulit;
    }
    
    public void setJenisKulit(String jenisKulit) {
        this.jenisKulit = jenisKulit;
    }
    public String getPekerjaan() {
        return this.pekerjaan;
    }
    
    public void setPekerjaan(String pekerjaan) {
        this.pekerjaan = pekerjaan;
    }




}


