package pojo;
// Generated Oct 22, 2020 6:44:34 PM by Hibernate Tools 4.3.1

import DAO.DAODokter;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;




/**
 * DataDokter generated by hbm2java
 */
@ManagedBean
public class DataDokter  implements java.io.Serializable {


     private Integer idDokter;
     private String namaDokter;
     private String jadwalDokter;
     private String jam;

       public String save_dokter(){
         DAODokter add =new DAODokter();
         add.addDokter(this);
         return "DataDokterAdmin";
     }
     
   
    
    public DataDokter() {
    }

    public DataDokter(String namaDokter, String jadwalDokter, String jam) {
       this.namaDokter = namaDokter;
       this.jadwalDokter = jadwalDokter;
       this.jam = jam;
    }
   
    public Integer getIdDokter() {
        return this.idDokter;
    }
    
    public void setIdDokter(Integer idDokter) {
        this.idDokter = idDokter;
    }
    public String getNamaDokter() {
        return this.namaDokter;
    }
    
    public void setNamaDokter(String namaDokter) {
        this.namaDokter = namaDokter;
    }
    public String getJadwalDokter() {
        return this.jadwalDokter;
    }
    
    public void setJadwalDokter(String jadwalDokter) {
        this.jadwalDokter = jadwalDokter;
    }
    public String getJam() {
        return this.jam;
    }
    
    public void setJam(String jam) {
        this.jam = jam;
    }




}


