package pojo;
// Generated Oct 22, 2020 6:44:34 PM by Hibernate Tools 4.3.1

import DAO.DAOReservasi;
import java.util.List;
import javax.faces.bean.ManagedBean;




/**
 * Reservation generated by hbm2java
 */
@ManagedBean
public class Reservation  implements java.io.Serializable {


     private Integer noReservation;
     private String idPasien;
     private String jenisTreatment;
     private String jumlah;
     private String tanggal;
     private String jam;
     private String konsul;
     
    public String save_reservasi(){
         DAOReservasi add = new DAOReservasi();
         add.add_reservasii(this);
         return "DataReservasiAdmin";
     }
     public String save_reservasiUser(){
         DAOReservasi add =new DAOReservasi();
         add.add_reservasii(this);
         return "LihatReservasi";
     }
     public List<Reservation> getAllRecords(){
         DAOReservasi rsrv = new DAOReservasi();
         List<Reservation> lRsrv = rsrv.retrieveDataReservasi();
         return lRsrv;
     }
     public String getById(){
         String No_Reservation = noReservation.toString();
         DAOReservasi rsrv = new DAOReservasi();
        List<Reservation> lRsrv = rsrv.getbyID(No_Reservation);
            noReservation = lRsrv.get(0).noReservation;
            idPasien = lRsrv.get(0).idPasien;
            jenisTreatment = lRsrv.get(0).jenisTreatment;
            jumlah = lRsrv.get(0).jumlah;
            tanggal = lRsrv.get(0).tanggal;
            jam = lRsrv.get(0).jam;
            konsul = lRsrv.get(0).konsul;
            return "EditDataReservasi";
     }
     public String getByIduser(){
         String No_Reservation = noReservation.toString();
         DAOReservasi rsrv = new DAOReservasi();
        List<Reservation> lRsrv = rsrv.getbyID(No_Reservation);
            noReservation = lRsrv.get(0).noReservation;
            idPasien = lRsrv.get(0).idPasien;
            jenisTreatment = lRsrv.get(0).jenisTreatment;
            jumlah = lRsrv.get(0).jumlah;
            tanggal = lRsrv.get(0).tanggal;
            jam = lRsrv.get(0).jam;
            konsul = lRsrv.get(0).konsul;
            return "LihatReservasiUser";
     }
     public String edit(){
         DAOReservasi rsrv = new DAOReservasi();
         rsrv.editReservasi(this);
         idPasien ="";
         jenisTreatment ="";
         jumlah="";
         tanggal="";
         jam="";
         konsul="";
         return "DataReservasiAdmin";
     }
     public void delete(int id){
          DAOReservasi rsrv = new DAOReservasi();
         rsrv.deleteReservasi(id);
     }
    public Reservation() {
    }

    public Reservation(String idPasien, String jenisTreatment, String jumlah, String tanggal, String jam, String konsul) {
       this.idPasien = idPasien;
       this.jenisTreatment = jenisTreatment;
       this.jumlah = jumlah;
       this.tanggal = tanggal;
       this.jam = jam;
       this.konsul = konsul;
    }
   
    public Integer getNoReservation() {
        return this.noReservation;
    }
    
    public void setNoReservation(Integer noReservation) {
        this.noReservation = noReservation;
    }
    public String getIdPasien() {
        return this.idPasien;
    }
    
    public void setIdPasien(String idPasien) {
        this.idPasien = idPasien;
    }
    public String getJenisTreatment() {
        return this.jenisTreatment;
    }
    
    public void setJenisTreatment(String jenisTreatment) {
        this.jenisTreatment = jenisTreatment;
    }
    public String getJumlah() {
        return this.jumlah;
    }
    
    public void setJumlah(String jumlah) {
        this.jumlah = jumlah;
    }
    public String getTanggal() {
        return this.tanggal;
    }
    
    public void setTanggal(String tanggal) {
        this.tanggal = tanggal;
    }
    public String getJam() {
        return this.jam;
    }
    
    public void setJam(String jam) {
        this.jam = jam;
    }
    public String getKonsul() {
        return this.konsul;
    }
    
    public void setKonsul(String konsul) {
        this.konsul = konsul;
    }




}


