package pojo;
// Generated Oct 22, 2020 6:44:34 PM by Hibernate Tools 4.3.1

import DAO.DAOLoginAdmin;
import java.util.List;
import javax.faces.bean.ManagedBean;




/**
 * TblAdmin generated by hbm2java
 */
@ManagedBean
public class TblAdmin  implements java.io.Serializable {


     private Integer idAdmin;
     private String usernameAdmin;
     private String passwordAdmin;

     public void save_admin(){
         DAOLoginAdmin add = new DAOLoginAdmin();
         add.add_admin(this);
     }
     public String login_admin(){
            DAOLoginAdmin uDao = new DAOLoginAdmin();
            List<TblAdmin> adm = uDao.getBy(usernameAdmin, passwordAdmin);
            try {
             if(adm != null)
            {
                usernameAdmin = adm.get(0).usernameAdmin;
                passwordAdmin = adm.get(0).passwordAdmin;
                return "LihatData";
            }
         } catch (Exception e) {
                System.out.println(e);
         }
            
            return "failed";
}
    public TblAdmin() {
    }

    public TblAdmin(String usernameAdmin, String passwordAdmin) {
       this.usernameAdmin = usernameAdmin;
       this.passwordAdmin = passwordAdmin;
    }
   
    public Integer getIdAdmin() {
        return this.idAdmin;
    }
    
    public void setIdAdmin(Integer idAdmin) {
        this.idAdmin = idAdmin;
    }
    public String getUsernameAdmin() {
        return this.usernameAdmin;
    }
    
    public void setUsernameAdmin(String usernameAdmin) {
        this.usernameAdmin = usernameAdmin;
    }
    public String getPasswordAdmin() {
        return this.passwordAdmin;
    }
    
    public void setPasswordAdmin(String passwordAdmin) {
        this.passwordAdmin = passwordAdmin;
    }




}


