package pojo;
// Generated Oct 22, 2020 6:44:34 PM by Hibernate Tools 4.3.1

import DAO.DAOLoginUser;
import java.util.List;
import javax.faces.bean.ManagedBean;




/**
 * TblUser generated by hbm2java
 */
@ManagedBean
public class TblUser  implements java.io.Serializable {


     private Integer idUser;
     private String username;
     private String password;

     public String save_user(){
         DAOLoginUser add = new DAOLoginUser();
         add.add_user(this);
         return "LoginUser";
     }
     public String login_user(){
            DAOLoginUser uDao = new DAOLoginUser();
            List<TblUser> us = uDao.getBy(username, password);
            try {
             if(us != null)
            {
                username = us.get(0).username;
                password = us.get(0).password;
                return "HomepageReservasi";
            }
         } catch (Exception e) {
                System.out.println(e);
         }
            
            return "failed";
}
    public TblUser() {
    }

    public TblUser(String username, String password) {
       this.username = username;
       this.password = password;
    }
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


